name: Terraform Apply

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7.0.1

      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@v3.0.0
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Install SOPS
        env:
          SOPS_VERSION: v3.12.1
        run: |
          curl -sLO https://github.com/getsops/sops/releases/download/${SOPS_VERSION}/sops-${SOPS_VERSION}.linux.amd64
          curl -sLO https://github.com/getsops/sops/releases/download/${SOPS_VERSION}/sops-${SOPS_VERSION}.checksums.txt
          sha256sum --check --ignore-missing sops-${SOPS_VERSION}.checksums.txt
          chmod +x sops-${SOPS_VERSION}.linux.amd64
          sudo mv sops-${SOPS_VERSION}.linux.amd64 /usr/local/bin/sops
          sops --version

      - name: Decrypt Secrets for Terraform
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        run: |
          sops decrypt config/users.enc.yaml > config/users.yaml
          sops decrypt config/groups.enc.yaml > config/groups.yaml

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4.0.1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_domain: ${{ secrets.GWS_DOMAIN }}
          TF_VAR_customer_id: ${{ secrets.GWS_CUSTOMER_ID }}
          TF_VAR_target_service_account: ${{ secrets.GWS_TARGET_SERVICE_ACCOUNT }}
          TF_VAR_default_user_password: ${{ secrets.GWS_DEFAULT_USER_PASSWORD }}
          TF_VAR_osc_access_key_id: ${{ secrets.OSC_ACCESS_KEY_ID }}
          TF_VAR_osc_secret_key_id: ${{ secrets.OSC_SECRET_KEY_ID }}

      - name: Remove decrypted files
        run: |
          rm -f config/users.yaml config/groups.yaml